- docker-compose.yml
Only merge after this has been merged and the docker container built
https://github.com/ministryofjustice/manage-recalls-e2e-tests/pull/new/update_manage-recalls-api_port
> Update manage recalls api port

- README.md
[PUD-67][AN] README additions re. Mike's local running scripts only.
[PUD-67]: https://dsdmoj.atlassian.net/browse/PUD-67
> [PUD-67][AN] README additions re. Mike's local running scripts.

- README.md
- src/test/java/cucumber/pages/OffenderProfilePage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
Add an assertion for 'create recall'
> PUD-189 create recall

- README.md
- serenity.properties
- src/test/java/cucumber/pages/AssessRecallPage.java
- src/test/java/cucumber/pages/FindAnOffenderPage.java
- src/test/java/cucumber/pages/OffenderProfilePage.java
- src/test/java/cucumber/pages/PpudPage.java
- src/test/java/cucumber/pages/TodoRecallsListPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
PUD-219  E2E: Update for minimal assess offender view - via To Do list also
Note:  download revocation doc test not working versus local processes either before or after this PR.
> PUD-219  E2E: Update for minimal assess offender view

- src/test/java/cucumber/pages/DecisionOnRecallRecommendationPage.java
- src/test/java/cucumber/pages/LastReleaseDetailsPage.java
- src/test/java/cucumber/pages/PoliceContactDetailsPage.java
- src/test/java/cucumber/pages/RecallAuthorisationPage.java
- src/test/java/cucumber/pages/RecallDetailsPage.java
- src/test/java/cucumber/pages/RecallReceivedPage.java
- src/test/java/cucumber/pages/RecallRecommendationPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
e2e tests for 
1. enter latest release info, 
2. enter local police info 
3. date and time of the recall request received from probation service
https://dsdmoj.atlassian.net/browse/PUD-317
https://dsdmoj.atlassian.net/browse/PUD-248
https://dsdmoj.atlassian.net/browse/PUD-253
> e2e tests for enter latest release info, enter local police info and date and time of the recall request received from probation service, 

- src/test/java/cucumber/pages/LastReleaseDetailsPage.java
- src/test/java/cucumber/pages/PpudPage.java
- src/test/java/cucumber/pages/RecallDetailsPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
Including sentence length for PUD-410
> PUD-247 - Extend E2E for sentence info fields

- src/test/java/cucumber/pages/DecisionOnRecallRecommendationPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
- clean up steps (use a single attemptsTo and merge dependent steps)
> PUD-144: Assert on recall length

- .circleci/config.yml
Wasn't actually working before.
> PUD-454: Use override env vars

- README.md
- src/test/java/cucumber/pages/CreateDossierDownloadDossierAndLetterPage.java
- src/test/java/cucumber/pages/PpudPage.java
- src/test/java/cucumber/pages/RecallAuthorisationPage.java
- src/test/java/cucumber/pages/RecallNotificationDownloadPage.java
- src/test/java/cucumber/pages/UploadRecallDocumentsPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
https://dsdmoj.atlassian.net/browse/PUD-516 - download dossier
https://dsdmoj.atlassian.net/browse/PUD-531 - download recall notification
also, uploaded documents now open in new tabs.
For all opened documents, switch to the new tab and check the URL matches the clicked link href.
> Open docs in new tabs

- src/test/java/cucumber/pages/RecallDetailsPage.java
- src/test/java/cucumber/pages/RecallPreConsNamePage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
https://dsdmoj.atlassian.net/browse/PUD-459
> PUD-459 - Pre-cons main name

- README.md
- autofill-extension-import.csv
- src/test/java/cucumber/pages/CreateDossierDownloadDossierAndLetterPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
Also, add Autofill chrome extension data in CSV
> PUD-168 check dossier for accuracy

- src/test/java/cucumber/pages/AssessARecallPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
> PUD-181: Verify 'booked by' is shown on details view

- src/test/java/cucumber/pages/ProbationDetailsPage.java
- src/test/java/cucumber/pages/RecallCheckAnswersPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
Merge https://github.com/ministryofjustice/manage-recalls-ui/pull/198 first
> PUD-616 - Local Delivery Unit

- .circleci/config.yml
- ci-local-mode-docker/Dockerfile
- serenity.properties
- src/test/java/cucumber/pages/PpudPage.java
- src/test/java/cucumber/pages/UploadRecallDocumentsPage.java
- src/test/java/cucumber/pages/UserDetailsPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- only take screenshots on failures
- take full page screenshots
- run without headless flag as there is a bug in chromedriver when getting current url of a 2nd tab
- use screenplay for file upload
> PUD-558: Ensure test fails if Internal error when opening pdf.

- README.md
- src/test/java/cucumber/pages/PoliceContactDetailsPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
PUD-1119  police force: E2E migration to use auto-fill
> PUD-1119  police force: E2E migration to use auto-fill

- README.md
- autofill-extension-import.csv
Book a recall:
- licence name
- precons name
- police force autocomplete
- missing documents text
> Updates to autofill chrome extension config

- src/test/java/cucumber/pages/UserDetailsPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
This reverts commit 8b788fade30dc8b4aa8d31b24fa43d055be26c5e.
> Revert "Update save button reference on user details page (#128)"

- src/test/java/cucumber/pages/PoliceContactDetailsPage.java
- start-local-services.sh
PUD-1132 E2E fix (plus some extended service start-up timeouts)
> PUD-1132 E2E fix (plus some extended service start-up timeouts)

- src/test/java/cucumber/pages/CreateANewDossierPage.java
- src/test/java/cucumber/pages/CreateANewReasonsForRecallPage.java
- src/test/java/cucumber/pages/CreateANewRecallNotificationPage.java
- src/test/java/cucumber/pages/CreateANewRevocationOrderPage.java
- src/test/java/cucumber/pages/RecallCheckAnswersPage.java
- src/test/java/cucumber/pages/ViewRecallPage.java
- src/test/java/cucumber/steps/NavigationSteps.java
- src/test/resources/features/managerecalls/ManageRecall.feature
PUD-1133, PUD-1046, PUD-1047, PUD-1183
> Add coverage for regenerating documents

- cypress/integration/notInCustody.feature
- cypress/integration/stepDefinitions/assess.js
- start-local-services.sh
- Use WireMock postcode API when running locally
> PUD-1253: Validate Not in custody FTR appears on Not in Custody tab and remains assigned to caseworker once assessment is complete

- .circleci/config.yml
ref: https://mojdt.slack.com/archives/C0223AGGQU8/p1644234238888359?thread_ts=1644232343.195209&cid=C0223AGGQU8
> Separate out the wait step in the deploy checks

- README.md
- cypress/fixtures/recall.js
- cypress/integration/inCustody.feature
- cypress/integration/notInCustody.feature
- cypress/integration/rescind.feature
- cypress/integration/stepDefinitions/book.js
- cypress/integration/stepDefinitions/stop.js
- cypress/integration/stop.feature
- move rescind to its own feature
- add backgrounds
> PUD-1451: Stop a recall

- .circleci/config.yml
- cypress.json
- docker-compose.yml
- start-local-services.sh
- Update the redis image to 6.2
- Update redis to use a password (this is more representative of how it will be used on AWS)
- Add in a redis-commander setup so we can look at the contents of redis easily (useful for debugging)
> Update Redis setup

- README.md
ref: https://mojdt.slack.com/archives/C02D2NEF9CJ/p1647956032772679
> Add the MoJ github repo compliance badge
